/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2013-08-28 19:52:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import by.parf.checkers.service.Constant;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/c.tld", Long.valueOf(1376830888000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t  <head>\r\n");
      out.write("        <title>Bootstrap 101 Template</title>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <!-- Bootstrap -->\r\n");
      out.write("        <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("        <!--[if lt IE 9]>\r\n");
      out.write("          <script src=\"../../assets/js/html5shiv.js\"></script>\r\n");
      out.write("          <script src=\"../../assets/js/respond.min.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("        <style type=\"text/css\">\r\n");
      out.write("    \t\t#header {\r\n");
      out.write("    \t\t\tmargin: 0 auto;\r\n");
      out.write("    \t\t\tfloat:none;\r\n");
      out.write("    \t\t\twidth: 500px;\r\n");
      out.write("    \t\t\tmargin-top: 40px;\r\n");
      out.write("    \t\t}\r\n");
      out.write("\r\n");
      out.write("    \t\t#mainList {\r\n");
      out.write("    \t\t\tmargin: 0 auto;\r\n");
      out.write("    \t\t\twidth: 540px;\r\n");
      out.write("    \t\t\tmargin-top: 50px;\r\n");
      out.write("    \t\t}\r\n");
      out.write("\r\n");
      out.write("    \t\t#evalTable {\r\n");
      out.write("    \t\t/*\ttext-align: center;*/\r\n");
      out.write("    \t\t}\r\n");
      out.write("\r\n");
      out.write("    \t\t.match {\r\n");
      out.write("    \t\t\tmargin-top: 100px;\r\n");
      out.write("    \t\t}\r\n");
      out.write("\r\n");
      out.write("    \t</style>\r\n");
      out.write("      </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <style>\r\n");
      out.write("\r\n");
      out.write("        </style>\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response,  Constant.URL_HEADER_PAGE, out, false);
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"mainList\">\r\n");
      out.write("            <div class=\"match\">\r\n");
      out.write("                <div class=\"panel panel-default\">\r\n");
      out.write("                    <div class=\"panel-heading\">БАТЭ - Смаргонь</div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"panel-body\">\r\n");
      out.write("                        <table class=\"table table-hover\" id=\"evalTable\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>Участник</th>\r\n");
      out.write("                                    <th>Прогноз</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr >\r\n");
      out.write("                                    <td>Kiryl Parfiankou</td>\r\n");
      out.write("                                    <td>7:0</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr >\r\n");
      out.write("                                    <td>Oleg Nesterove</td>\r\n");
      out.write("                                    <td>6:1</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"panel-footer\">\r\n");
      out.write("                        <form class=\"form-inline\" role=\"form\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label class=\"sr-only\" for=\"team1Goals\">БАТЭ</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"team1Goals\" placeholder=\"БАТЭ\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label class=\"sr-only\" for=\"team2Goals\">Смаргонь</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"team2Goals\" placeholder=\"Смаргонь\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-default\">Отправить</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                        <div class=\"match\">\r\n");
      out.write("                <div class=\"panel panel-default\">\r\n");
      out.write("                    <div class=\"panel-heading\">БАТЭ - Смаргонь</div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"panel-body\">\r\n");
      out.write("                        <table class=\"table table-hover\" id=\"evalTable\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>Участник</th>\r\n");
      out.write("                                    <th>Прогноз</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr class=\"success\">\r\n");
      out.write("                                    <td>Kiryl Parfiankou</td>\r\n");
      out.write("                                    <td>7:0</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"warning\">\r\n");
      out.write("                                    <td>Oleg Nesterove</td>\r\n");
      out.write("                                    <td>6:1</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"warning\">\r\n");
      out.write("                                    <td>Vlad Ytsenko</td>\r\n");
      out.write("                                    <td>4:0</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"danger\">\r\n");
      out.write("                                    <td>Ruslan Abramov</td>\r\n");
      out.write("                                    <td>1:2</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                        <div class=\"match\">\r\n");
      out.write("                <div class=\"panel panel-default\">\r\n");
      out.write("                    <div class=\"panel-heading\">БАТЭ - Смаргонь</div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"panel-body\">\r\n");
      out.write("                        <table class=\"table table-hover\" id=\"evalTable\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>Участник</th>\r\n");
      out.write("                                    <th>Прогноз</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr class=\"success\">\r\n");
      out.write("                                    <td>Kiryl Parfiankou</td>\r\n");
      out.write("                                    <td>7:0</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"warning\">\r\n");
      out.write("                                    <td>Oleg Nesterove</td>\r\n");
      out.write("                                    <td>6:1</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"warning\">\r\n");
      out.write("                                    <td>Vlad Ytsenko</td>\r\n");
      out.write("                                    <td>4:0</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"danger\">\r\n");
      out.write("                                    <td>Ruslan Abramov</td>\r\n");
      out.write("                                    <td>1:2</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                        <div class=\"match\">\r\n");
      out.write("                <div class=\"panel panel-default\">\r\n");
      out.write("                    <div class=\"panel-heading\">БАТЭ - Смаргонь</div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"panel-body\">\r\n");
      out.write("                        <table class=\"table table-hover\" id=\"evalTable\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>Участник</th>\r\n");
      out.write("                                    <th>Прогноз</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr class=\"success\">\r\n");
      out.write("                                    <td>Kiryl Parfiankou</td>\r\n");
      out.write("                                    <td>7:0</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"warning\">\r\n");
      out.write("                                    <td>Oleg Nesterove</td>\r\n");
      out.write("                                    <td>6:1</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"warning\">\r\n");
      out.write("                                    <td>Vlad Ytsenko</td>\r\n");
      out.write("                                    <td>4:0</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"danger\">\r\n");
      out.write("                                    <td>Ruslan Abramov</td>\r\n");
      out.write("                                    <td>1:2</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                        <div class=\"match\">\r\n");
      out.write("                <div class=\"panel panel-default\">\r\n");
      out.write("                    <div class=\"panel-heading\">БАТЭ - Смаргонь</div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"panel-body\">\r\n");
      out.write("                        <table class=\"table table-hover\" id=\"evalTable\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>Участник</th>\r\n");
      out.write("                                    <th>Прогноз</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr class=\"success\">\r\n");
      out.write("                                    <td>Kiryl Parfiankou</td>\r\n");
      out.write("                                    <td>7:0</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"warning\">\r\n");
      out.write("                                    <td>Oleg Nesterove</td>\r\n");
      out.write("                                    <td>6:1</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"warning\">\r\n");
      out.write("                                    <td>Vlad Ytsenko</td>\r\n");
      out.write("                                    <td>4:0</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"danger\">\r\n");
      out.write("                                    <td>Ruslan Abramov</td>\r\n");
      out.write("                                    <td>1:2</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("        <script src=\"http://code.jquery.com/jquery.js\"></script>\r\n");
      out.write("        <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("         <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("            $('.selectpicker').selectpicker({\r\n");
      out.write("                 style: 'btn-info',\r\n");
      out.write("                 size: 4\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            $('#requestPopup').modal({\r\n");
      out.write("                keyboard: true,\r\n");
      out.write("                show: false,\r\n");
      out.write("                backdrop: true\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $('#sendRequet').on('click', function() {\r\n");
      out.write("                var w = 400; // popup width\r\n");
      out.write("                var h = 400; // popip hieght\r\n");
      out.write("                var popupPosition = {\r\n");
      out.write("                    left: (screen.width/2)-(w/2) + 'px',\r\n");
      out.write("                    top: (screen.height/2)-(h/2) + 'px',\r\n");
      out.write("                    width: w,\r\n");
      out.write("                    height: h  \r\n");
      out.write("                }\r\n");
      out.write("                $( '#requestPopup' ).modal('show');\r\n");
      out.write("                $( '#requestPopup' ).css(popupPosition);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $('form').form();\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
